name: Update Database
run-name: GitHub Actions is updating the database 🚀
on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE 
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4 
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install requirements.txt                               
        run: pip install -r requirements.txt
      - name: Run python file to process data
        run: python scripts/01-process-data.py
      - name: Set up yarn
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
      - name: Deploy data to vercel
        run: |-
          datasette publish vercel data/processed/opportunities.db \
            --token $VERCEL_TOKEN \
            --project opportunities-db
      - name: Config git
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Acton"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Automatic data update"